services:
  - type: web
    name: ilaunchapp
    runtime: node
    plan: starter
    buildCommand: npm install --force && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production